# Generated by Django 5.1.2 on 2024-11-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariants',
            name='variant_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='variants_thumbnails/'),
        ),
    ]
