# Generated by Django 5.1.2 on 2024-11-21 18:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_image', models.ImageField(upload_to='category')),
                ('category_name', models.CharField(db_index=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z, ]+$', 'Category name must only contain alphabetic characters')])),
                ('category_slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(default='')),
                ('is_active', models.BooleanField(default=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='category.category')),
            ],
            options={
                'ordering': ['parent_category__id'],
            },
        ),
    ]
