# Generated by Django 5.1.2 on 2024-11-21 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(db_index=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z,& ]+$', 'Category name must only contain alphabetic characters')]),
        ),
    ]
